version: '3.8'

services:
  # Development frontend with hot reload
  djobea-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: djobea-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000/api}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:8001}
      - NEXT_PUBLIC_WS_PORT=${NEXT_PUBLIC_WS_PORT:-8001}
      - ENABLE_AI_PREDICTIONS=${ENABLE_AI_PREDICTIONS:-true}
      - ENABLE_GEOLOCATION=${ENABLE_GEOLOCATION:-true}
      - ENABLE_REALTIME=${ENABLE_REALTIME:-true}
      - ENABLE_WHATSAPP=${ENABLE_WHATSAPP:-false}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - djobea-dev-network
    restart: unless-stopped
    command: npm run dev

networks:
  djobea-dev-network:
    driver: bridge
