version: '3.8'

services:
  # Frontend application
  djobea-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - NEXT_PUBLIC_WS_PORT=${NEXT_PUBLIC_WS_PORT}
    container_name: djobea-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_WS_PORT=${NEXT_PUBLIC_WS_PORT}
      - ENABLE_AI_PREDICTIONS=${ENABLE_AI_PREDICTIONS:-false}
      - ENABLE_GEOLOCATION=${ENABLE_GEOLOCATION:-false}
      - ENABLE_REALTIME=${ENABLE_REALTIME:-false}
      - ENABLE_WHATSAPP=${ENABLE_WHATSAPP:-false}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - djobea-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (optionnel)
  nginx:
    image: nginx:alpine
    container_name: djobea-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - djobea-network
    depends_on:
      - djobea-frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  djobea-network:
    driver: bridge

volumes:
  logs:
    driver: local
